import nodemailer from 'nodemailer';
import { getFirmProfile } from '../routes/settings';
interface Invoice {
  invoice_number: string;
  client_name: string;
  client_email: string;
  total: number;
  date: string;
  date_paid: string | null;
  status: string;
}
async function getTransporter() {
  const profile = getFirmProfile();
  const SMTP_HOST = profile.smtp_host || process.env.SMTP_HOST;
  const SMTP_PORT = profile.smtp_port ? profile.smtp_port.toString() : process.env.SMTP_PORT;
  const SMTP_USER = profile.smtp_user || process.env.SMTP_USER;
  const SMTP_PASS = profile.smtp_pass || process.env.SMTP_PASS;

  if (SMTP_HOST && SMTP_USER && SMTP_PASS) {
    return nodemailer.createTransport({
      host: SMTP_HOST,
      port: parseInt(SMTP_PORT || '587', 10),
      secure: parseInt(SMTP_PORT || '587', 10) === 465,
      auth: { user: SMTP_USER, pass: SMTP_PASS },
    });
  }
  // Use Ethereal test account for development
  const testAccount = await nodemailer.createTestAccount();
  console.log('📧 Using Ethereal test account:', testAccount.user);
  return nodemailer.createTransport({
    host: 'smtp.ethereal.email',
    port: 587,
    secure: false,
    auth: { user: testAccount.user, pass: testAccount.pass },
  });
}
export async function sendInvoiceEmail(
  invoice: Invoice,
  pdfBuffer: Buffer
): Promise<{ messageId: string; previewUrl?: string | false }> {
  const transporter = await getTransporter();
  const profile = getFirmProfile();
  const fromAddress = profile.firm_email || process.env.SMTP_FROM || 'billing@legalfirm.com';
  const firmName = profile.firm_name || 'Legal Billing';
  const info = await transporter.sendMail({
    from: `"${firmName}" <${fromAddress}>`,
    to: invoice.client_email,
    subject: `Invoice ${invoice.invoice_number} - ₹${invoice.total.toFixed(2)}`,
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <h2 style="color: #1a1a2e;">Invoice ${invoice.invoice_number}</h2>
        <p>Dear ${invoice.client_name},</p>
        <p>Please find attached your invoice for <strong>₹${invoice.total.toFixed(2)}</strong>.</p>
        <table style="width: 100%; border-collapse: collapse; margin: 20px 0;">
          <tr>
            <td style="padding: 8px; border-bottom: 1px solid #eee; font-weight: bold;">Invoice Number</td>
            <td style="padding: 8px; border-bottom: 1px solid #eee;">${invoice.invoice_number}</td>
          </tr>
          <tr>
            <td style="padding: 8px; border-bottom: 1px solid #eee; font-weight: bold;">Date</td>
            <td style="padding: 8px; border-bottom: 1px solid #eee;">${invoice.date}</td>
          </tr>
          ${invoice.date_paid ? `
          <tr>
            <td style="padding: 8px; border-bottom: 1px solid #eee; font-weight: bold;">Date Paid</td>
            <td style="padding: 8px; border-bottom: 1px solid #eee;">${invoice.date_paid}</td>
          </tr>
          ` : ''}
          <tr>
            <td style="padding: 8px; border-bottom: 1px solid #eee; font-weight: bold;">Amount Due</td>
            <td style="padding: 8px; border-bottom: 1px solid #eee; font-size: 18px; color: #1a1a2e; font-weight: bold;">₹${invoice.total.toFixed(2)}</td>
          </tr>
        </table>
        <p>Thank you for your business.</p>
        <p style="color: #999; font-size: 12px;">This invoice was generated by LexLedger.</p>
      </div>
    `,
    attachments: [{
      filename: `Fee Memo No- ${invoice.invoice_number} ${invoice.client_name} ${invoice.date}.pdf`,
      content: pdfBuffer,
      contentType: 'application/pdf',
    }],
  });
  const previewUrl = nodemailer.getTestMessageUrl(info);
  if (previewUrl) {
    console.log('📧 Preview URL:', previewUrl);
  }
  return { messageId: info.messageId, previewUrl };
}
export async function sendReminderEmail(
  invoice: Invoice
): Promise<{ messageId: string; previewUrl?: string | false }> {
  const transporter = await getTransporter();
  const profile = getFirmProfile();
  const fromAddress = profile.firm_email || process.env.SMTP_FROM || 'billing@legalfirm.com';
  const firmName = profile.firm_name || 'Legal Billing';
  const info = await transporter.sendMail({
    from: `"${firmName}" <${fromAddress}>`,
    to: invoice.client_email,
    subject: `Payment Reminder: Invoice ${invoice.invoice_number} - ₹${invoice.total.toFixed(2)}`,
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <h2 style="color: #dc3545;">Payment Reminder</h2>
        <p>Dear ${invoice.client_name},</p>
        <p>This is a friendly reminder that payment for the following invoice is outstanding:</p>
        <table style="width: 100%; border-collapse: collapse; margin: 20px 0;">
          <tr>
            <td style="padding: 8px; border-bottom: 1px solid #eee; font-weight: bold;">Invoice Number</td>
            <td style="padding: 8px; border-bottom: 1px solid #eee;">${invoice.invoice_number}</td>
          </tr>
          <tr>
            <td style="padding: 8px; border-bottom: 1px solid #eee; font-weight: bold;">Original Date</td>
            <td style="padding: 8px; border-bottom: 1px solid #eee;">${invoice.date}</td>
          </tr>
          ${invoice.date_paid ? `
          <tr>
            <td style="padding: 8px; border-bottom: 1px solid #eee; font-weight: bold;">Date Paid</td>
            <td style="padding: 8px; border-bottom: 1px solid #eee; color: #dc3545; font-weight: bold;">${invoice.date_paid}</td>
          </tr>
          ` : ''}
          <tr>
            <td style="padding: 8px; border-bottom: 1px solid #eee; font-weight: bold;">Amount Due</td>
            <td style="padding: 8px; border-bottom: 1px solid #eee; font-size: 18px; color: #dc3545; font-weight: bold;">₹${invoice.total.toFixed(2)}</td>
          </tr>
        </table>
        <p>Please arrange payment at your earliest convenience. If you have already made the payment, please disregard this reminder.</p>
        <p>Thank you,<br>Legal Billing Team</p>
        <p style="color: #999; font-size: 12px;">This reminder was generated by LegalBill.</p>
      </div>
    `,
  });
  const previewUrl = nodemailer.getTestMessageUrl(info);
  if (previewUrl) {
    console.log('📧 Reminder Preview URL:', previewUrl);
  }
  return { messageId: info.messageId, previewUrl };
}